### ISSUE TITLE
ModuleNotFoundError: No module named 'Sim3DR_Cython', How to solve this question?

### ISSUE THREAD

**Issue by gjgjgjfff** [Arthur151/ROMP#413]

**Comment by Arthur151** [comment]
If you have properly install the latest simple-romp, this would not happen

pip install --upgrade simple-romp

**Comment by gjgjgjfff** [comment]
谢谢你的回复，这个问题已经解决，还有一个问题，按照您的步骤，安装pytorch3d和所需库，执行pip install https://github.com/Arthur151/ROMP/releases/download/v1.1/pytorch3d-0.6.1-cp37-cp37m-linux_x86_64.whl
和pip install -r requirements.txt 后，执行sh scripts/V1_train.sh，服务器报错ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory，是什么原因呢？

**Comment by Arthur151** [comment]
没有安装好conda10.2。
如果要直接pip安装的话，请注意：

To directly install via pip, you need to install CUDA 10.2 first (For Ubuntu, runsudo apt-get install cuda-10-2).

**Comment by gjgjgjfff** [comment]
必须要cuda10.2吗？学校的服务器好像最高支持10.1，而且我没有权力更新cuda，我用的是torch1.8.1+cu101，python3.7
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  On   | 00000000:06:00.0 Off |                    1 |
| N/A   31C    P0    28W / 250W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  On   | 00000000:2F:00.0 Off |                    0 |
| N/A   30C    P0    26W / 250W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-PCIE...  On   | 00000000:86:00.0 Off |                    0 |
| N/A   31C    P0    25W / 250W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-PCIE...  On   | 00000000:D8:00.0 Off |                    0 |
| N/A   30C    P0    27W / 250W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
